### ISSUE TITLE
WebVR Camp @SENAI Santa Cecília Julho/2017

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#1]
## Goal: 
Executar WebVR Camp no SENAI Santa Cecília em Julho/2017.

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
**Planejamento**
- [x] Definir OKR
- [x] Convidar voluntários para apoio na organização
- [x] Abrir página no Reps
- [x] Abrir budget request
- [x] Confirmar data no lugar do evento e enviar requerimentos
- [x] Comprar, solicitar e/ou produzir material necessário

**Marketing**
- [x] Criar página no Eventbrite
- [x] Criar imagens para Facebook, Twitter e Eventbrite
- [x] Divulgação nas redes sociais
- [x] Informar assessoria de imprensa
- [x] Informar comunidade

**Pré evento**
- [x] E-mail para os participantes antes do evento
- [x] Comprar, solicitar e/ou produzir material necessário
- [x] Enviar lista de participantes para a recepção do lugar do evento

**Comment by barrosgg** [comment]
Reps: https://reps.mozilla.org/e/webvr-camp-senai-santa-cecilia/

**Comment by barrosgg** [comment]
Eventbrite: https://www.eventbrite.com.br/e/a-frame-webvr-com-html-e-entity-component-registration-35103567716

**Comment by barrosgg** [comment]
- [x] Mandar produzir camisetas
- [x] Mandar produzir poster

**Comment by barrosgeraldo** [comment]
- [ ] enviar notificação/confirmação de interesse aos participantes.

**Comment by cpswsg** [comment]
Coffee break requested!

**Comment by barrosgg** [comment]
report pending, over this to @meldenne.

**Comment by barrosgg** [comment]
receipts pending

**Comment by barrosgg** [comment]
Ready. Closing.
