### ISSUE TITLE
CSS Grids [7/Out]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#10]

**Comment by cyb3113** [comment]
O Senai ainda não conseguiu confirmar esta data.  Podemos tentar em outro lugar. Talvez ThoughtWorks?

**Comment by barrosgg** [comment]
Vamos planejar primeiro e depois ver a data, primeiro precisamos definir as pessoas, criar uma proposta do workshop, então procurar o local.

**Comment by barrosgg** [comment]
@cyb3113, a Alda & mais uma pessoa, está evangelizando CSS Grids layout, você poderia checar com elas a possibilidade de fazer um workshop? E informa-las que é necessário trabalhar conosco para criar o curriculum do workshop.

**Comment by cyb3113** [comment]
@barrosgeraldo vou falar com a Alda sim.  Não sei quem é a outra pessoas, mas tentarei me informar.

**Comment by barrosgg** [comment]
A Alda que me falou que tinha outra pessoa que estava evangelizando, então certamente ela sabe.

**Comment by barrosgeraldo** [comment]
A Alda que me falou que tinha outra pessoa que estava evangelizando, então certamente ela sabe.

**Comment by barrosgg** [comment]
@cyb3113, vamos escalar essa atividade para o futuro, digamos próximo ano, e vamos tomar nosso tempo para o Firefox Sprint. #15
