### ISSUE TITLE
Dive Into Rust @SENAI Santa Cecilia [09/Set]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#11]

**Comment by cyb3113** [comment]
Estou procurando lanchinhos vegans.  Qual o valor que poderemos gastar? Têm ideia de quantidade?

**Comment by barrosgeraldo** [comment]
Vou compartilhar contigo assim que possível a nossa planilha de custos aprovados.

**Comment by barrosgg** [comment]
ooops, vamos manter esse off ainda desde que é só em setembro.

**Comment by leoyvens** [comment]
Dia 9 não rola para mim, supondo que eu seria o Rust speaker neste também.

**Comment by barrosgg** [comment]
Oi @leodasvacas, ótimo ter você aqui, assim podemos trabalhar com os planejamentos diretamente aqui. Desde que movemos o workshop de Belo Horizonte para setembro, não vou considerar organizar este. 

Vamos mover para outro mês, você gostaria de sugerir uma data em que você estaria disponível? Eu estou pensando em organizar algo em São Carlos e Araraquara, temos solicitações da comunidade open source de lá. O que você acha?

**Comment by leoyvens** [comment]
Estou livre em relação a datas, São Carlos e Araraquara parece bom!

**Comment by barrosgg** [comment]
É então, existe uma demanda lá por causa das universidades e tem comunidades open source e startups interessadas.

**Comment by barrosgg** [comment]
O que acha do dia 30 em São Carlos ou Araraquara?

**Comment by leoyvens** [comment]
@barrosgeraldo Acho bom!

**Comment by barrosgg** [comment]
Não, tivemos retorno do pessoal de São Carlos, vamos fechar essa. @cyb3113, avise o SENAI que infelizmente não teremos atividades esse mês.
