### ISSUE TITLE
Mozilla's Data Privacy Day [28/Jan/18]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#12]

**Comment by barrosgg** [comment]
Vou aproveitar esse para fazer o treinamento em recursos com a Cybelle.

**Comment by cyb3113** [comment]
como vai ser um evento grandinho, precisamos começar a planejar ASAP

**Comment by barrosgg** [comment]
Exato, por isso estou escalando para começar a ideação desde já.

**Comment by barrosgg** [comment]
https://paper.dropbox.com/doc/Mozillas-Data-Privacy-Day-dyOjRZzUnVMHt823dWbTz
