### ISSUE TITLE
Agendar Reunião para Sprint

### ISSUE THREAD

**Issue by cyb3113** [mozillabrasil/sao-paulo#15]
Agendar reunião para Sprint.
Tópicos:
-  que dia?
-  onde?
-  quem?
-  orçamento

**Comment by barrosgg** [comment]
Eu discuti um pouco com vocês pessoalmente, então a minha proposta é:

- 6 de outubro / 19h as 22h
- _sugestão de lugares?_
- @cynthiapereira e @cyb3113 
- Orçamento para bolo com Firefox logo + 1 bebida, e outro material descartável necessário
- Máx 20 pessoas

**Comment by cyb3113** [comment]
- 6f das 19-22h dificil encontrar um lugar de boas com interenet decente. então estou pensando aqui com meu zíperes, quantas pessoas serão? Eu, @barrosgeraldo e a @cynthiapereira ? Ou mais gente?

**Comment by barrosgg** [comment]
Máx 20 pessoas como mencionado.

**Comment by cyb3113** [comment]
Eu não tenho ideia de lugar a essa hora com internet boa.  Alguma sugestão?

**Comment by barrosgg** [comment]
Sem ideias por agora também :(

**Comment by barrosgg** [comment]
Depois de uma reunião com Cynthia, Cybelle, decidimos que essa campanha não é interessante por agora. Vamos trabalhar em uma festa de lançamento para novembro.
