### ISSUE TITLE
Software Freedom Day 2017 São Carlos

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#16]
## Goal: 
Organizar palestras de IHR + Mozilla no evento.

**Comment by barrosgg** [comment]
@felipez3r0, não é mais possível solicitar recursos para esse evento, muito em cima. Vou levar o swag que eu tenho aqui, não sei exatamente o que tenho, mas Solana me enviará algumas coisas de Berlin, mas deve demorar muito.

**Comment by barrosgg** [comment]
Palestra de IHR no evento pendente de aprovação, é necessário garantir que os slides estejam prontos.

https://github.com/mozilla/OpenDesign/issues/144

**Comment by barrosgg** [comment]
https://reps.mozilla.org/e/software-freedom-day-2017-sao-carlos/

**Comment by barrosgg** [comment]
Necessário criar um banner para redes sociais. TBDT

**Comment by barrosgg** [comment]
template daft based on Mozilla Italia
![photo_2017-09-04_19-21-15](https://user-images.githubusercontent.com/14970832/30039375-3ab33f34-91a6-11e7-967d-1769f391bec6.jpg)

**Comment by barrosgg** [comment]
Aguardando aprovação da palestra para seguir aqui.

**Comment by felipez3r0** [comment]
@barrosgeraldo Estou aguardando o retorno sobre minha palestra também. A ideia é apresentar algumas das novas tecnologias, falar sobre o Nightly e mostrar as possibilidades de contribuição com a Mozilla e com a comunidade Brasileira.

**Comment by felipez3r0** [comment]
@barrosgeraldo A palestra que enviei não ficou entre as selecionadas. Em todo caso se precisar de ajuda com algo me avise! Estou à disposição 😄

**Comment by barrosgg** [comment]
Oi @felipez3r0, ahhh. Mas você não quer falar sobre Internet Health Report junto comigo?

Ontem eu trabalhei nos slides, esse é o slide original[1] (acompanha notas do speaker), e esse é o novo slide[2] que criei ontem alinhado com a branding nova.

[1] https://docs.google.com/presentation/d/1dH1Yr027_uPSOnAoGalfa3kr_psbp0-w1JNmo5S_Ig0/edit?usp=sharing
[2] https://www.dropbox.com/s/1t8h8ffoqloigas/mozilla_internet_health_report_speaker_decks.pdf?dl=0

**Comment by barrosgg** [comment]
Tudo pronto.

**Comment by barrosgg** [comment]
https://geraldobarros.me/internet-health-software-freedom-day-2017-sao-carlos/
