### ISSUE TITLE
MozCoffee São Paulo - Outubro 2017

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#17]

**Comment by cpswsg** [comment]
- [x] Entrar em contato com o pessoal da JeffGroup.
- [x] Agendar uma reunião para o mês de setembro. 
- [x] Verificar quem são os voluntários que podem atender o evento.
- [x] Abrir budget para o MozCoffee

**Comment by cpswsg** [comment]
- Encontro será no dia 13/10 às 15h na sede da JeffreyGroup
- Participação confirmada: eu, @barrosgeraldo e @cyb3113 
- Bug aberto, aguardando aprovação.

**Comment by cpswsg** [comment]
Reps Event: https://reps.mozilla.org/e/mozcoffee-sao-paulo-october-2017/

**Comment by herbert-wagner** [comment]
OIiii e bem no dia do meu aniversário kkkk

**Comment by herbert-wagner** [comment]
OIiii e bem no dia do meu aniversário kkkk

**Comment by cpswsg** [comment]
Bug aprovado!

**Comment by rberaldo** [comment]
Olá! Confirmo presença também.

**Comment by herbert-wagner** [comment]
Confirmo a presença

**Comment by cpswsg** [comment]
Conforme solicitação da assessoria de imprensa da Mozilla o evento foi reagendado para o dia 20 de outubro no mesmo horário e local. 

@herbert-wagner e @rberaldo por favor, verifiquem se vocês conseguem participar.

**Comment by herbert-wagner** [comment]
Olá dia 20 não vou poder comparecer :(

**Comment by barrosgg** [comment]
Olá pessoal, Mozcoffee cancelado pela JeffreyGroup.

**Comment by cpswsg** [comment]
Como citado anteriormente o pessoal da JeffreyGroup cancelou a parte deles, porém precisamos definir ASAP algumas ações, faremos o encontro no **sábado dia 21/10 às 11h no SENAI Santa Cecília.** Endereço consta no portal do Reps.

@herbert-wagner e @rberaldo sei que foi de última hora, mas gostaria de saber se vocês conseguem participar. :-)

P.S. Depois do nosso encontro acontecerá o workshop sobre Rust no mesmo local.

**Comment by rberaldo** [comment]
@cynthiapereira peço desculpas por não ter respondido anteriormente. Não pude ir, infelizmente! Gostaria de dizer que finais de semana são melhores do que dias de semana, já que não vivo em São Paulo. Esse final de semana em específico tinha um compromisso, no entanto. Espero que o evento seja bom!

**Comment by cpswsg** [comment]
@rberaldo Achei que você fosse de São Paulo, sem problemas! Nesse evento, ocorreu dois cancelamentos de última hora por parte da assessoria de imprensa, o que deixo as coisas um pouco corridas. Contudo, vou te dar um spoiler: 19 de Novembro save the date! :-)
