### ISSUE TITLE
Dive Into Rust @SENAI Santa Cecilia [Outubro]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#18]

**Comment by barrosgg** [comment]
@cyb3113, temos alguma data reservada para outubro no SENAI?

**Comment by barrosgg** [comment]
@leodasvacas, outubro você está disponível em 7, 14 ou 21 para workshop de Rust?

**Comment by leoyvens** [comment]
@barrosgeraldo Outubro meus sábados estão livres tanto pra Campinas como SP.

**Comment by barrosgg** [comment]
@cyb3113, dia 7 ou 14 de outubro é possível organizar algo no SENAI? Estou querendo reservar o dia 21 para Campinas.

**Comment by barrosgg** [comment]
@cyb3113, a semana do dia 14 tem um feriado prolongado, conhecido popularmente no Brasil como feriadão, logo não parece bom porque muitas pessoas vão viajar.

**Comment by cyb3113** [comment]
Verei se dia 7 de outubro eles tem disponibilidade. Semana do dia 14 acho péssima idéia e do dia 21, próxima a London Calling rsrs

**Comment by barrosgg** [comment]
Ok, aguardando retorno.

**Comment by cyb3113** [comment]
Email enviado ao senai. Esperando a resposta deles.

**Comment by barrosgg** [comment]
pendente  de confirmação final

**Comment by cyb3113** [comment]
Senai confirmado. Aleluia irmãos!

**Comment by barrosgg** [comment]
@cyb3113 @leodasvacas, por favor confirmem a participação direto no Reps: https://reps.mozilla.org/e/dive-into-rust-senai-santa-cecilia-2/

**Comment by barrosgg** [comment]
@cyb3113 @leodasvacas, por favor adicionem todos os custos na [planilha de orçamento](https://docs.google.com/spreadsheets/d/1R6ZZc38KsSkAfrznO4Z5N24-WikurbsH1iydBxQsgXs/edit?usp=sharing), apenas em BRL na coluna "Budget (local)". Se desejar adicionar um novo item, adicione o nome do item ou serviço na coluna "Item/Service", coloque o valor total em BRL na coluna "Budget (local)" e detalhes sobre o item ou serviço na coluna "Detailed information about item".

**Comment by barrosgg** [comment]
Eventbrite: https://www.eventbrite.com.br/e/mergulhando-em-rust-o-futuro-da-programacao-de-sistemas-4-registration-38145874337

Como foi conversado, para evitar desistências, vamos divulgar e abrir inscrições com 1/2 semanas antes do evento.

**Comment by barrosgg** [comment]
Budget solicitado: https://bugzilla.mozilla.org/show_bug.cgi?id=1403004

**Comment by barrosgg** [comment]
Evento, pronto, encerrado.
