### ISSUE TITLE
Dive Into Rust @Campinas city [Outubro]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#19]
Organizar e executar uma [oficina de Rust](https://www.eventbrite.com.br/e/mergulhando-em-rust-o-futuro-da-programacao-de-sistemas-2-registration-36876136517) em Campinas no próximo mês.

**Comment by barrosgg** [comment]
Dependendo da disponibilidade do Leonardo, podemos organizar este em outubro na Superlógica Labs.

https://github.com/mozillabrasil/sao-paulo/issues/18

**Comment by barrosgg** [comment]
Vou só verificar se o dia 21 de outubro foi reservado pela Cybelle no SENAI, caso contrário definimos essa data para algo em Campinas.

**Comment by barrosgg** [comment]
Verificado, dia 21 está livre, good to go.

**Comment by barrosgeraldo** [comment]
Solicitação de evento para Superlógica foi feito, solicitei o dia 21 de outubro.

**Comment by barrosgeraldo** [comment]
Pendente de retorno da Superlógica

**Comment by barrosgg** [comment]
Over this to @rogeriofox from LHC.

**Comment by barrosgg** [comment]
@rogeriofox, obrigado pela orientação, e-mail enviado ao LHC. :)

**Comment by barrosgg** [comment]
https://lhc.net.br/wiki/2017/10/28_Mergulhando_em_Rust_by_Mozilla

**Comment by barrosgg** [comment]
https://reps.mozilla.org/e/dive-into-rust-laboratorio-hacker-de-campinas/

**Comment by barrosgg** [comment]
New date: **28 OCT 2017 Saturday 13:00-18:00**

**Comment by barrosgg** [comment]
aguardando aprovação de budget

**Comment by barrosgg** [comment]
Budget aprovado.

**Comment by barrosgg** [comment]
Eventbrite: https://www.eventbrite.com.br/e/mergulhando-em-rust-o-futuro-da-programacao-de-sistemas-3-registration-37744693394

**Comment by barrosgg** [comment]
Próxima tarefa: reservar coffee break.

**Comment by barrosgg** [comment]
Evento encerrado.

**Comment by barrosgg** [comment]
@leodasvacas, obrigado pelo workshop. ;)
Vamos a nossa listinha pós evento:
- Blog post
- Recibos por e-mail (Uber)
