### ISSUE TITLE
MozCoffee São Paulo 2017

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#2]
## Goal: 
Organizar a Mozilla Weekend São Paulo 2017

**Comment by barrosgg** [comment]
check de disponibilidade de datas enviado aos voluntários

**Comment by barrosgg** [comment]
Recebendo atualizações...
- [x] Geraldo Barros [1/2]
- [x] Cynthia P [1/2]
- [x] Cybelle O [1/2]
- [ ] Airton Z
- [x] Mariana M [2]
- [x] Felipe S [1]

**Comment by barrosgg** [comment]
check finalizado

**Comment by barrosgg** [comment]
OKR e planejamento: https://paper.dropbox.com/doc/Mozilla-Sao-Paulo-Weekend-2017-6QphGxEpNzSy3jYi6EbWq

**Comment by cpswsg** [comment]
Reps: https://reps.mozilla.org/e/mozcoffee-sao-paulo/

**Comment by barrosgg** [comment]
- Agenda autorizada com Vanielli
- Budget solicitada

**Comment by barrosgg** [comment]
orçamento aprovado.

**Comment by barrosgg** [comment]
over this to Cynthia. É necessário solicitar o coffe break.

**Comment by cpswsg** [comment]
Coffee break requested!

**Comment by cpswsg** [comment]
Blog post is coming soon.

**Comment by barrosgg** [comment]
Ready. Closing.
