### ISSUE TITLE
Agendar treinamento de recursos e planejamento com Cybelle

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#8]

**Comment by barrosgg** [comment]
Cybelle, podemos fazer o treinamento na próxima sexta-feira?

**Comment by cyb3113** [comment]
@barrosgeraldo 6f tenho reunião da cryptoparty.  Posso 2f e 4f da semana que vem. O que acha ? :)

**Comment by barrosgg** [comment]
Vamos marcar segunda a noite?

**Comment by cyb3113** [comment]
Combinado! Só me diz o horário ;)

**Comment by barrosgg** [comment]
20h, okiedokie?

**Comment by cyb3113** [comment]
🤘🏻🖤

**Comment by barrosgg** [comment]
Since I'm up for reps resources track, I'll waiting for final approval and I'll start this training for all community.
