### ISSUE TITLE
WebVR Camp @Hyper VR Festival [16/Set]

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/sao-paulo#9]

**Comment by barrosgg** [comment]
Nós fomos convidados para desenvolver atividades neste evento, a proposta principal é um WebVR Camp workshop, e atividades com a Foxy (fantasia) desde que é um festival.

Aguardando confirmação por parte do organizador do evento.

**Comment by cpswsg** [comment]
@barrosgeraldo Por favor, me deixe saber se a presença da Foxy será realmente necessária para fazer os preparativos.

**Comment by barrosgg** [comment]
não tivemos retorno após relatar os critérios para presença no evento, closing.
